[theme]
base = "light"
primaryColor = "#003366"  # Bleu marine
backgroundColor = "#F7F7F7"  # Gris clair
secondaryBackgroundColor = "#FFFFFF"  # Blanc pur
textColor = "#2C3E50"  # Gris fonc√©, presque noir
font = "Sans serif"
